volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  fastapi:
    build:
      context: ./camp_scout_service
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./camp_scout_service:/app
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://adminuser:passcamp@postgres:5432/campscout_db
      SIGNING_KEY: testing0signkey
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 90
      PORT: 8000
      NPS_API_KEY: ${NPS_API_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000

  postgres:
    image: postgres:15.3-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: passcamp
      POSTGRES_USER: adminuser
      POSTGRES_DB: campscout_db
    ports:
      - 15432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: adminuser@campscout.com
      PGADMIN_DEFAULT_PASSWORD: campscout1
      PGADMIN_DISABLE_POSTFIX: 1
